### ISSUE TITLE
Why are the colors messed up or different?

### ISSUE THREAD

**Issue by Redm828** [Dabomstew/gambatte-speedrun#2] opened 2017-03-22 19:35 UTC
Colors on this emulator are VERY different than those on BGB and console. 

Gambatte: https://puu.sh/uUWZH/28af2caf54.png
BGB: https://puu.sh/uUWpK/1481cef216.png
Console (from Gunners stream) https://puu.sh/uUWLI/16bee86d36.png

BGB and Console look the same but it is clear that Gambatte is off. If there's a way to change this I would love to but I don't know anything like this.

**Comment by Dabomstew** [comment] 2017-03-23 22:02
This behavior is caused by this color translation function:

https://github.com/sinamas/gambatte/blob/master/libgambatte/src/video.cpp#L33

As far as I *know* (this might be wrong), Gambatte tries to make the colors look like they would on an actual GBC screen by using the mix of rgb channel values that it does. If you just change it to translate from GBC colors to RGB colors in a perfectly linear way, you get what is shown on your BGB and GBP screenshots. I might add an option for this behavior in a future release but it certainly isn't a priority right now.

(you can also make BGB look like Gambatte does by using the "GBC LCD colors" option which is what makes me believe that this is how things work as they are)

**Comment by Dabomstew** [comment] 2017-10-11 08:58
Closed by release 4 / r614.

**Closed by Dabomstew** 2017-10-11 08:58 UTC
